steps:
  - name: hashicorp/terraform:light
    id: Terraform Init
    dir: terraform
    entrypoint: terraform
    args: ["init"]

  - name: hashicorp/terraform:light
    id: Terraform Plan
    dir: terraform
    entrypoint: terraform
    args: ["plan", "-out=tfplan"]

  - name: hashicorp/terraform:light
    id: Terraform Apply
    dir: terraform
    entrypoint: terraform
    args: ["apply", "-auto-approve", "tfplan"]

# Deploy Cloud Run Function from cf1/
  - name: gcr.io/cloud-builders/gcloud
    id: Deploy Cloud Run
    dir: cf1-checker
    args:
      [
        "run", "deploy", "pod-grabber",
        "--source=.",
        "--region=europe-west2",
        "--platform=managed",
        "--allow-unauthenticated"
      ]

options:
  logging: CLOUD_LOGGING_ONLY